#This file is generated by ModuleSync, do not edit.

source ENV['GEM_SOURCE'] || "https://rubygems.org"

def location_for(place, version = nil)
  if place =~ /^(git[:@][^#]*)#(.*)/
    [version, { :git => $1, :branch => $2, :require => false}].compact
  elsif place =~ /^file:\/\/(.*)/
    ['>= 0', { :path => File.expand_path($1), :require => false}]
  else
    [place, version, { :require => false}].compact
  end
end

group :unit_tests do
  gem 'rake',                                                       :require => false
  gem 'metadata-json-lint',                                         :require => false
  gem 'rspec-puppet-facts',                                         :require => false
  gem 'puppetlabs_spec_helper',                                     :require => false
  gem 'rspec-puppet', '>= 2.3.2',                                   :require => false
  gem 'parallel_tests',                                             :require => false
  gem 'simplecov',                                                  :require => false
  gem 'rubocop',                                                    :require => false
  gem 'puppet-lint-unquoted_string-check',                          :require => false
  gem 'puppet-lint-leading_zero-check',                             :require => false
  gem 'puppet-lint-variable_contains_upcase',                       :require => false
  gem 'puppet-lint-absolute_classname-check',                       :require => false
  gem 'puppet-lint-trailing_comma-check',                           :require => false
  gem 'puppet-lint-file_ensure-check',                              :require => false
  gem 'puppet-lint-empty_string-check',                             :require => false
  gem 'puppet-lint-undef_in_function-check',                        :require => false
  gem 'puppet-lint-version_comparison-check',                       :require => false
  gem 'puppet-lint-appends-check',                                  :require => false
  gem 'puppet-lint-spaceship_operator_without_tag-check',           :require => false
  gem 'puppet-lint-classes_and_types_beginning_with_digits-check',  :require => false
  gem 'puppet-lint-param-docs',                                     :require => false
  gem 'puppet-lint-absolute_template_path',                         :require => false
  gem 'puppet-lint-numericvariable',                                :require => false
  gem 'puppet-lint-strict_indent-check',                            :require => false
  gem 'puppet-lint-resource_reference_syntax',                      :require => false
  gem 'puppet-lint-usascii_format-check',                           :require => false
  gem 'puppet-lint-duplicate_class_parameters-check',               :require => false
end
group :development do
  gem 'puppet-blacksmith',  :require => false
  gem 'travis',             :require => false
  gem 'travis-lint',        :require => false
  gem 'guard-rake',         :require => false
end
group :system_tests do
  gem 'beaker-rspec',                  *location_for(ENV['BEAKER_RSPEC_VERSION'] || '>= 3.4')
  gem 'beaker',                        *location_for(ENV['BEAKER_VERSION'])
  gem 'beaker-puppet_install_helper',  :require => false
end

gem 'facter', *location_for(ENV['FACTER_GEM_VERSION'])
gem 'puppet', *location_for(ENV['PUPPET_GEM_VERSION'])

if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end
