name 'evenup-kibana'
version '0.2.0'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
summary 'Installs and configures Kibana3.'
description 'Installs and configures Kibana3 from packages.'
project_page 'https://github.com/evenup/evenup-kibana'
dependency 'evenup/apache', '>= 2.1.0'
