#This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'
require 'rspec-puppet-facts'
include RspecPuppetFacts

RSpec.configure do |config|
    config.filter_run focus: true
    config.run_all_when_everything_filtered = true
end

# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError # rubocop:disable Lint/HandleExceptions
end
